### ISSUE TITLE
Javascript error when executing "return Date.now();" when using Internet Explorer

### ISSUE THREAD

**Issue by danielviolin** [facebookarchive/huxley#15]
My Huxley version is 0.4. Selenium Standalone Server is 2.35.0. IEDriverServer is 2.35.1. OS is Windows Server 2008 R2. Browser is IE 8.
I found that this code 

``` python
start_time = d.execute_script('return Date.now();')
```

produces javascript error when using IE while Firefox is ok.

Why not using Python time to get start time?

Below is my traceback. Thank you.

---

C:\Program Files\Python27\Scripts\huxley.exe --record

---

Running Huxley file: Huxleyfile

---

Running test: toggle
Begin record
Traceback (most recent call last):
  File "C:\Program Files\Python27\Scripts\huxley-script.py", line 9, in <module>

  load_entry_point('Huxley==0.4', 'console_scripts', 'huxley')()
  File "build\bdist.win-amd64\egg\huxley\cmdline.py", line 153, in main
  File "C:\Program Files\Python27\lib\site-packages\plac_core.py", line 309, in
call
    cmd, result = parser_from(obj).consume(arglist)
  File "C:\Program Files\Python27\lib\site-packages\plac_core.py", line 195, in
consume
    return cmd, self.func(_(args + varargs + extraopts), *_kwargs)
  File "build\bdist.win-amd64\egg\huxley\cmdline.py", line 130, in _main
  File "build\bdist.win-amd64\egg\huxley\main.py", line 109, in main
  File "build\bdist.win-amd64\egg\huxley\run.py", line 109, in record
  File "C:\Program Files\Python27\lib\site-packages\selenium-2.32.0-py2.7.egg\se
lenium\webdriver\remote\webdriver.py", line 397, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "C:\Program Files\Python27\lib\site-packages\selenium-2.32.0-py2.7.egg\se
lenium\webdriver\remote\webdriver.py", line 165, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python27\lib\site-packages\selenium-2.32.0-py2.7.egg\se
lenium\webdriver\remote\errorhandler.py", line 152, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: u"JavaScript error (WARN
ING: The server did not provide any stacktrace information)\nCommand duration or
 timeout: 168 milliseconds\nBuild info: version: '2.35.0', revision: 'c916b9d',
time: '2013-08-12 15:42:01'\nSystem info: os.name: 'Windows Server 2008 R2', os.
arch: 'x86', os.version: '6.1', java.version: '1.7.0_25'\nSession ID: c8b4e699-d
daf-4f20-8996-34b4dd619916\nDriver info: org.openqa.selenium.ie.InternetExplorer
Driver\nCapabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBe
havior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSes
sion=false, browserName=internet explorer, enableElementCacheCleanup=true, unexp
ectedAlertBehaviour=dismiss, version=8, ie.usePerProcessProxy=false, ignoreProte
ctedModeSettings=false, cssSelectorsEnabled=true, requireWindowFocus=false, init
ialBrowserUrl=http://localhost:3598/, handlesAlerts=true, ie.forceCreateProcessA
pi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitch
es=, takesScreenshot=true}]" ; Screenshot: available via screen ; Stacktrace: Me
thod newInstance0 threw an error in None

**Comment by petehunt** [comment]
I've just merged a fix for this; thanks!
