### ISSUE TITLE
Using other browsers question

### ISSUE THREAD

**Issue by lazyxiong** [facebookarchive/huxley#24]
Hello,

this is awesome tool - thanks for making this available !
I have a question about how to define other browsers, default is firefox
as I can see. I couldn't find any env variable that would control this,
so I made some changes to main.py and cmdline.py to support this
via env variables. But in case I re-invented the wheel, please tell me how
to it properly :)

Thanks !
Alex

**Comment by YoDK** [comment]
Did you take a look at : https://github.com/facebook/huxley/pull/19

**Comment by lazyxiong** [comment]
Thanks - I certainly missed that !:) Though, the changes I have made locally enable this functionality via env variables, this solution of putting it in a Huxleyfile should work for me too.

**Comment by petehunt** [comment]
Let's move the discussion to #19
