### ISSUE TITLE
Test a website page that requires authentication

### ISSUE THREAD

**Issue by pivotal-casebook** [facebookarchive/huxley#28]
Hi!

We are trying to test our website page that requires us to login first. However huxley fails to record a session in this case because we visited two pages during the session, i.e the login page and the actual that we wanted to test.

Do you have any ideas on how to test such website with huxley. Also, is it possible to use huxley in our existing ruby on rails application.

Thanks,
Rajat & Keith

**Comment by jacobangel** [comment]
From the best practices:

> Don't test a live app. Use mocking to make your components reliable instead. If you hit your live app, failures in any number of places could trigger false failures in your UI tests. Instead of hitting a real URL in your app, create a dedicated test URL for Huxley to hit that uses mocking (and perhaps dependency injection) to isolate your UI component as much as possible. Huxley is completely unopinionated; use whatever tools you want to do this.

You may get more out of huxley if you create a test page with the isolated component, instead of trying to use this as a high level integration test. You might be better off using a phantom js if you're looking for something to crawl your website/app.

**Comment by petehunt** [comment]
Hey @pivotal-casebook --

So, even though I think that there are better ways to do this per the best practices like @jacobangel said, I would like to support this use case if we can do it reliably. See https://github.com/facebook/huxley/pull/12 for a pull request that adds support for this feature as well as some of my concerns about its reliability. Would definitely appreciate any thoughts you would have on it.

With that said we already have an issue for this at https://github.com/facebook/huxley/issues/10 so I am going to close this out in favor of keeping that one open. Feel free to chime in on that issue or the pull request to share any additional context you may have. Thanks for the report!
