### ISSUE TITLE
Do we want pixel perfect matches?

### ISSUE THREAD

**Issue by DirkStevens** [facebookarchive/huxley#30]
Like this idea a lot...

Is there a way to perform some form of "fuzzy" compare?

Imagine I've just changed a color in my app and now all tests have to be recreated because the Hux strats tripping over each and every reference screenshot?

. D

**Comment by chenglou** [comment]
SImply running `huxley` will re-record the screenshots again without comparison. That's what you want.

**Comment by DirkStevens** [comment]
As rendering engines differ accross OS/browsers/versions - how would you setup cross-browser testing?
- Create a test in Chrome
- Re-run test for other browsers targets?

**Comment by chenglou** [comment]
This partially solve your problem: https://github.com/facebook/huxley#how-do-i-use-a-remote-webdriver-server

About multiple browsers, I've opened an issue: #32
