### ISSUE TITLE
Entire page ScreenShots

### ISSUE THREAD

**Issue by lmartins** [facebookarchive/huxley#35]
Im trying to implement Huxley as way to test css regression, using the project Styleguide as the canonical source where the tests happen.

Although i get the idea of single function testing, most tests require a full page screenshot, instead of just a small portion. 

Any way I can do that?

**Comment by lmartins** [comment]
Never mind, the reason that the screenshot wasn't full page height was related to the app itself.

**Comment by edmadcap** [comment]
Can Huxley create entire page screenshots? Or, does it take screenshots of the viewport only?

For example, if the viewport is 1,000px tall, but the page is 5,000px tall, will Huxley create the 5,000px tall image?

And, can Huxley take screenshots of pages of various heights (without having to enter a setting for each)?

**Comment by lmartins** [comment]
@edmadcap If you pass a 5000px it will make a 5000px tall image, unless the page ends before that, case in which it will create an image with the height of the page. Im not sure of the implications of passing high values for pages height but ultimately that was what I ended up doing. 

This off course only makes sense when you are testing full pages, which makes sense in my case because im testing style guide pages, not live applications.

**Comment by chenglou** [comment]
@edmadcap the height is either the default or the one you specified. If you pass `x`, it takes `x` (unless `x` is bigger than your screen of course). And currently you must pass the various heights.

**Comment by edmadcap** [comment]
Ok, great. Glad to hear that Huxley can take a screenshot of the entire page (not just the portion that is visible in the viewport).
I will probably just set the height to be a high number like lmartins is doing.
