### ISSUE TITLE
About stealing browser focus

### ISSUE THREAD

**Issue by chenglou** [facebookarchive/huxley#36]
Is the current focus stealing strategy is limited to `--record`? I see the actual screen shots are taken from a window behind the one in which I operated, as to remove input focus, etc. But when running in any other mode no such focus stealing is being done, which makes the screenshots taken during recording useless since they'll always be different than one the taken by those other modes.

**Comment by petehunt** [comment]
Well, it's done during re-record and playback so we can consistently record without focus. The screenshots from the original record were always useless.

**Comment by chenglou** [comment]
What I mean is for `--playback-only` and plain `huxley`, the dummy browser window doesn't show up.
