### ISSUE TITLE
Cannot install: "Could not find any downloads that satisfy the requirement PIL==1.1.7 (from huxley)"

### ISSUE THREAD

**Issue by nathanbirrell** [facebookarchive/huxley#41]
On installation, I receive this when the Huxley installation reaches PIL.

```
Could not find any downloads that satisfy the requirement PIL==1.1.7 (from huxley)
Some externally hosted files were ignored (use --allow-external PIL to allow).
Cleaning up...
No distributions at all found for PIL==1.1.7 (from huxley)
Storing debug log for failure in /Users/nathan/Library/Logs/pip.log
```

Have installed Pillow separately, still receiving issue. 

![screenshot 2014-01-23 09 32 59](https://f.cloud.github.com/assets/4300215/1979721/3b77ed3c-83b5-11e3-8af2-6963efd0d94d.png)

**Comment by paazmaya** [comment]
Do you have Pillow 2.2.1 installed, as that is the version required in the `setup.py`?
https://pypi.python.org/pypi/Pillow

You could also change the value in `setup.py` to 2.2.2, install that version (currently latest of 2.2 branch) and run `python setup.py install`...

**Comment by nathanbirrell** [comment]
Thanks, @paazmaya, yes that seems to have fixed it. I believe the issue is still a problem when installing through `pip` though. This solution has worked for me though. Cheers.

**Comment by emanlove** [comment]
@paazmaya: It looks as if the latest version of Huxley posted on PyPI, which is where I am assuming your call to pip grabbed the packages from, is 0.4 and was posted 2013-10-08. The change from Pill to Pillow occurred with e5396e79d22703ec1aceac1c833274fb167ecc0a merged on 2013-11-13. So the version on PyPI is a little old. You might be able to get @petehunt to make a new release.

**Comment by petehunt** [comment]
Good idea, https://github.com/facebook/huxley/issues/44
