### ISSUE TITLE
Launching two firefox browsers in the record mode

### ISSUE THREAD

**Issue by bharatvamsi** [facebookarchive/huxley#8]
Hi, I've installed Huxley using zip file on windows 7 64-bit. I've two selenium-webdriver versions (2.0.32 and 2.0.33) installed on my system. When I launched Huxley in record mode, it is launching two firefox browsers and from the second browser it is taking the screen shots. When I quit from Huxley, script ends with an error saying that event function not able to record the events. In the resultant created file, "record.json" is empty.I'm using 'selenium-server-standalone-2.33.0.jar'.

Please assist in resolving this problem.

**Comment by bharatvamsi** [comment]
Following is the error received:

## D:\PythonAssignments\ImageComparison>huxley -r

## Running Huxley file: Huxleyfile

Running test: toggle
Begin record
Press enter to take a screenshot, or type Q+enter if you're done

1 screenshots taken
Press enter to take a screenshot, or type Q+enter if you're done

2 screenshots taken
Press enter to take a screenshot, or type Q+enter if you're done

3 screenshots taken
Press enter to take a screenshot, or type Q+enter if you're done

4 screenshots taken
Press enter to take a screenshot, or type Q+enter if you're done
q
Traceback (most recent call last):
  File "C:\Python27\Scripts\huxley-script.py", line 9, in <module>
    load_entry_point('Huxley==0.1', 'console_scripts', 'huxley')()
  File "C:\Python27\lib\site-packages\huxley-0.1-py2.7.egg\huxley\cmdline.py", line 126, in main
    sys.exit(plac.call(_main))
  File "C:\Python27\lib\site-packages\plac-0.9.1-py2.7.egg\plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "C:\Python27\lib\site-packages\plac-0.9.1-py2.7.egg\plac_core.py", line 195, in consume
    return cmd, self.func(_(args + varargs + extraopts), *_kwargs)
  File "C:\Python27\lib\site-packages\huxley-0.1-py2.7.egg\huxley\cmdline.py", line 105, in _main
    record=True
  File "C:\Python27\lib\site-packages\huxley-0.1-py2.7.egg\huxley\main.py", line 109, in main
    TestRun.record(local_d, d, (url, postdata), screensize, filename, diffcolor, sleepfactor, save_diff)
  File "C:\Python27\lib\site-packages\huxley-0.1-py2.7.egg\huxley\run.py", line 127, in record
    events = d.execute_script('return window._getHuxleyEvents();')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 397, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 165, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 152, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: u"window._getHuxleyEvents is not a function\nBuild info: version: '2.3
3.0', revision: '4e90c97', time: '2013-05-22 15:32:38'\nSystem info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1',
java.version: '1.6.0_25'\nDriver info: driver.version: unknown" ; Screenshot: available via screen ; Stacktrace: Method anonym
ous threw an error in https://accounts.google.com/SignUp?service=mail&continue=http%3A%2F%2Fmail.google.com%2Fmail%2F&ltmpl=de
fault

**Comment by petehunt** [comment]
The issue is that you're trying to navigate to a new page. This isn't currently supported, but we could build a feature to do so (it would require manually letting huxley know when you've changed pages via the console though)

**Comment by bharatvamsi** [comment]
Hi petehunt,
Thank you for the instant reply. I'm not navigating to a new page as I'm using "http://www.gmail.com" in huxley file. Please can you elaborate on this?

Regards,
vamsi.

**Comment by petehunt** [comment]
Hey @bharatvamsi -

Huxley is designed mainly for hitting test pages you've created rather than third-party sites. Gmail may take precautions to avoid the injection of third-party JS which Huxley requires to work. There may be ways to fix this but I think it's outside the scope of what Huxley is intended to do. You may be better off using Selenium/webdriver directly.

Let me know if you have any questions; thanks!

**Comment by bharatvamsi** [comment]
Hi Petehunt,

Thank you for sharing the detailed information.

Regards,
vamsi.
