### ISSUE TITLE
No Huxleyfile found

### ISSUE THREAD

**Issue by cyildirim** [facebookarchive/huxley#9]
I created a `Huxleyfile` like at tutorial and execute following command `huxley --record` but take `No Huxleyfile found` error. It is probably basic mistake but i can't understand. By the way my Huxleyfile at `examples/` directory.

**Comment by petehunt** [comment]
Are you running the command in the directory that contains the Huxleyfile?

**Comment by cyildirim** [comment]
It works. I knew it was quite easy. Thanks.
